export * from './lib/studies-backend.controller'
export * from './lib/studies-backend.service'
export * from './lib/studies-backend.module'
export * from './lib/participation/study-participation-backend.service'
export { StudyCollectionName } from './lib/study.schema'
