version: '3.9'

services:
  keycloak_postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.0
    depends_on:
      - keycloak_postgres
    #    restart: unless-stopped
    ports:
      - '8080:8080'
    command: ['start-dev', '--import-realm']
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: 'jdbc:postgresql://keycloak_postgres:5432/${KEYCLOAK_DB_NAME}'
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME: localhost
    volumes:
      - ./docker/keycloak/realms:/tmp/realm-exports
      - ./docker/keycloak/realms:/opt/keycloak/data/import
