export * from './lib/assignments-core-frontend.module'
export * from './lib/lib.routes'
export * from './lib/assignments.service'
export * from './lib/assignment-config-form-host/assignment-config-form-host.component'
export * from './lib/assignment-completion-process-host/assignment-completion-process-host.component'
