name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Build all apps
        if: github.event_name == 'pull_request'
        run: npx nx affected --target=build --parallel=3

      - name: Build affected apps
        if: github.event_name == 'push'
        run: npx nx run-many --target=build --parallel=3
