name: Format checks
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    uses: ./.github/workflows/setup.yml
    steps:
      - name: Check all files' formatting
        run: npx nx format:check
