name: Format checks
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup.yml

      - name: Check all files' formatting
        run: npx nx format:check
