name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    steps:
      - uses: ./.github/workflows/setup.yml
      - name: Test all projects
        if: github.event_name == 'pull_request'
        run: npx nx affected --target=test --parallel=3 --configuration=ci

      - name: Test affected projects
        if: github.event_name == 'push'
        run: npx nx run-many --target=test --parallel=3 --configuration=ci
